import {
  MEDIA_LIMITS,
  MESSENGER_ATTACHMENT_ACCEPT as UPLOAD_MESSENGER_ATTACHMENT_ACCEPT,
  MESSENGER_ATTACHMENT_MIME_TYPES,
} from '../../lib/mediaValidation'

export const MESSENGER_ATTACHMENT_ACCEPT = UPLOAD_MESSENGER_ATTACHMENT_ACCEPT
export const MESSENGER_MAX_ATTACHMENTS = MEDIA_LIMITS.selectionCount
export { MESSENGER_ATTACHMENT_MIME_TYPES }
